### ISSUE TITLE
Publish sheet: Publish sheet button / keyboard issues

### ISSUE THREAD

**Issue by megsfulton** [Automattic/portkey-android#537] opened 2020-09-17 00:42 UTC
>The Publish button is covered by the keyboard, and the bottom sheet can’t be scrolled up to make it visible.

>If you dismiss the keyboard, the Publish button is still not visible and swiping on the bottom sheet will dismiss it.

(Confirming device, think it's a Pixel 2 or 3XL)

**Comment by aforcier** [comment] 2020-10-23 02:25
Also reported in the Apps beta by @bummytime 

![IMG_3087](https://user-images.githubusercontent.com/9613966/96949251-6c997600-1522-11eb-8a52-8d3dadf35ff5.PNG)

> This slide up panel there gets “stuck” on my pixel 3 (Android 11). I cannot get it to slide up more unless I back out and try again.

**Comment by mzorz** [comment] 2020-10-23 13:25
I'm planning to look into it next week but in the meantime, any ideas that may pop off the top of your head about this one @jd-alexander ? 🙇

**Comment by jd-alexander** [comment] 2020-10-23 19:24
Thanks! I can take a look into this as well @mzorz thanks for the ping.

**Comment by jd-alexander** [comment] 2020-11-04 22:19
@mzorz I started looking into this and so far it seems as if it doesn't take place every time ie sometimes the publish button is covered and other times it isn't. I am going to work on consistently reproducing it so I can verify the issue is resolved when I try some fixes I have in mind.

**Comment by mzorz** [comment] 2020-11-04 22:49
Thanks for looking into this @jd-alexander ! 🙇 BTW I can reproduce 100% of the time with a Pixel 3 XL API 29 emulator so, this should make it easier to investigate the issue on your side too (but let me know if it doesn't happen there and we can maybe do something in sync time)
![sheet](https://user-images.githubusercontent.com/6597771/98176126-bb59ef00-1ed6-11eb-81b0-4445570440f5.gif)

**Comment by jd-alexander** [comment] 2020-11-05 18:43
Thanks for this @mzorz it helps! I will utilize the configurations you specified to continue my investigation.

**Comment by mzorz** [comment] 2020-11-06 00:19
Closing via https://github.com/wordpress-mobile/WordPress-Android/pull/13298 - great job @jd-alexander !

**Closed as completed by mzorz** 2020-11-06 00:19 UTC

**Comment by jd-alexander** [comment] 2020-11-06 00:50
Thanks, @mzorz I created an [issue](https://github.com/wordpress-mobile/WordPress-Android/issues/13299) in WP Android itself to track the [other issue with the overlaying](https://github.com/Automattic/stories-android/issues/537#issuecomment-714867147). I will create a PR with the fix for that shortly.

**Comment by jd-alexander** [comment] 2020-11-06 01:33
[This](https://github.com/Automattic/stories-android/issues/537#issuecomment-714867147 ) has been resolved https://github.com/wordpress-mobile/WordPress-Android/pull/13300
