### ISSUE TITLE
StringIndexOutOfBoundsException in SaveStoryGutenbergBlockUseCase

### ISSUE THREAD

**Issue by aforcier** [Automattic/portkey-android#615] opened 2020-12-02 01:56 UTC
I get this crash, it seems to happen using these steps:

* Start a new GB post
* Add a story block
* Don't edit the block or do anything, just exit the editor
* A draft is saved
* Crash

I get the crash on WPAndroid `alpha-260` (Wasabi debug build). I couldn't seem to reproduce this on the 16.3-rc-1 vanilla build, I'm not sure why.

cc @mzorz 

```
2020-12-02 10:53:04.789 4499-4499/org.wordpress.android.beta E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wordpress.android.beta, PID: 4499
    org.greenrobot.eventbus.EventBusException: Invoking subscriber failed
        at org.greenrobot.eventbus.EventBus.handleSubscriberException(EventBus.java:527)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:509)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501)
        at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -68
        at java.lang.String.substring(String.java:2064)
        at org.wordpress.android.ui.stories.SaveStoryGutenbergBlockUseCase.findAllStoryBlocksInPostAndPerformOnEachMediaFilesJson(SaveStoryGutenbergBlockUseCase.kt:104)
        at org.wordpress.android.ui.stories.SaveStoryGutenbergBlockUseCase.replaceLocalMediaIdsWithRemoteMediaIdsInPost(SaveStoryGutenbergBlockUseCase.kt:117)
        at org.wordpress.android.ui.uploads.MediaUploadReadyProcessor.replaceMediaFileWithUrlInPost(MediaUploadReadyProcessor.java:33)
        at org.wordpress.android.ui.uploads.UploadService.updatePostWithMediaUrl(UploadService.java:626)
        at org.wordpress.android.ui.uploads.UploadService.updatePostWithCurrentlyCompletedUploads(UploadService.java:474)
        at org.wordpress.android.ui.uploads.UploadService.updateOnePostModelWithCompletedAndFailedUploads(UploadService.java:722)
        at org.wordpress.android.ui.uploads.UploadService.doFinalProcessingOfPosts(UploadService.java:1008)
        at org.wordpress.android.ui.uploads.UploadService.stopServiceIfUploadsComplete(UploadService.java:685)
        at org.wordpress.android.ui.uploads.UploadService.onPostUploaded(UploadService.java:1096)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:501) 
        at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by mzorz** [comment] 2020-12-02 03:29
This crash seems to be related to an inconsistent state of a given Post. I can't reproduce here with these steps, because an empty block by itself won't run into these conditions. Seems there needs to be  a specific Post for which a Story block is found and then something else happens in `doFinalProcessingOfPosts` in `UploadService`.
When the UploadService is about to finish, it performs a call to `doFinalProcessingOfPosts` in which it goes through all media registered Posts, and then tries to process any pending media for them updating the contents of the Post.
The steps to reproduce here make the UploadService get triggered, and hence the offending Post is found (but it is not this specific empty Story block post the one to blame).

Will try and look further to try identify the actual culprit.

**Comment by aforcier** [comment] 2020-12-03 02:57
I placed a debugger and caught the actual post content being parsed before the crash, you were right it's not coming from the empty post but rather I must have a draft with pending media on that build:

```
<!-- wp:paragraph -->
<p>Post here</p>
<!-- /wp:paragraph -->

<!-- wp:jetpack/story {"mediaFiles":[{"alt":"","caption":"","id":"57","link":"file:///storage/emulated/0/Pictures/WordPress%20Beta/wp_story1606105374717_0.jpg","mime":"","type":"image","url":"file:///storage/emulated/0/Pictures/WordPress%20Beta/wp_story1606105374717_0.jpg"},{"alt":"","caption":"","id":"58","link":"file:///storage/emulated/0/Pictures/WordPress%20Beta/wp_story1606105375134_1.jpg","mime":"","type":"image","url":"file:///storage/emulated/0/Pictures/WordPress%20Beta/wp_story1606105375134_1.jpg"}]} -->
<div class="wp-block-jetpack-story wp-story"></div>
<!-- /wp:jetpack/story -->
```

Looks like having a block before the story might be the culprit.


```
val jsonString: String = content.substring(
		storyBlockStartIndex + HEADING_START.length,
		content.indexOf(HEADING_END))
```

 `HEADING_END` I think is matching the end of the first block, so the range for the story block substring ends before it starts. So we probably need to calculate `storyBlockStartIndex + HEADING_START.length` first and find the first `HEADING_END` after that index.

**Comment by aforcier** [comment] 2020-12-03 03:04
@mzorz I think I can take this one in this case so you can focus on the other issues, I'll test that fix ^ and open a PR if I'm correct.

**Comment by aforcier** [comment] 2020-12-03 04:11
Yep looks like that was it, after fixing the substring issue I repeated the steps with an empty block and there was no crash, plus I found the draft that was causing the crash and it had been saved remotely 👍 

PR up for review @mzorz : https://github.com/wordpress-mobile/WordPress-Android/pull/13525

**Comment by mzorz** [comment] 2020-12-03 13:07
Closing via https://github.com/wordpress-mobile/WordPress-Android/pull/13525

**Closed as completed by mzorz** 2020-12-03 13:07 UTC
Labels: [Type] Crash
